### ISSUE TITLE
Test Service

### ISSUE THREAD

**Issue by stdavis** [agrc/serverless-print-proxy#10]
We need a way to publish a test version that we can mess around with without affecting production.

Maybe just a separate function named "printproxy-test"? `sls deploy` deploys all functions in the service so we'd have to be careful with that command and always specify a specific function to deploy.

**Comment by steveoh** [comment]
can you explain the relationship between a function and a service

**Comment by stdavis** [comment]
It's like a project. I think that it's a serverless framework thing not specific to google cloud. Ref: https://serverless.com/framework/docs/providers/google/guide/services/

**Comment by stdavis** [comment]
I tried to define a second test function in `serverless.yml` today and `sls deploy function -f printproxytest` didn't do anything. [The serverless docs for GCP](https://serverless.com/framework/docs/providers/google/cli-reference/deploy/) make me think that it doesn't support deploying single functions. :( We may want to consider moving away from the serverless tool for this project.

**Comment by stdavis** [comment]
This may help in the future if we decide to switch to gcloud: https://stackoverflow.com/questions/49744470/creating-a-development-and-staging-environments-for-google-cloud-functions

**Comment by stdavis** [comment]
`gcp-terraform/print-proxy` is set up for a `dev` environment. Just waiting on the new way for projects to be created.

**Comment by stdavis** [comment]
We have a dev gcp project for this project now.
