### ISSUE TITLE
Travis env vars are stripped in external PR's

### ISSUE THREAD

**Issue by stdavis** [agrc/serverless-print-proxy#12]
Need to find a way around this: https://docs.travis-ci.com/user/pull-requests/#Pull-Requests-and-Security-Restrictions

**Comment by steveoh** [comment]
It seems to me you wouldn't want to work around that but work within that. 

You could pull/push the branch as yourself to get the CI to run in an authorized context.

Or add the folks that are involved as contributors?

**Comment by stdavis** [comment]
Not super excited about either of those options. I don't think that we want to give push access to everyone involved. I wonder if there's a better way to specify secure environment variables. I remember going back and forth on them.

**Comment by stdavis** [comment]
See #3
