### ISSUE TITLE
Doesn't work with Experience Builder

### ISSUE THREAD

**Issue by stdavis** [agrc/serverless-print-proxy#124]
When you attempt to input this project as a print utility service, the app returns a "service not supported" error. I've narrowed it down to this piece of code in `utility-selector.js`:
![image](https://user-images.githubusercontent.com/1326248/233212848-a4c6b680-6cd4-41db-bc61-692be2f9f996.png)

The issue is that print proxy's route to the print service is:
`/<accountNumber>/arcgis/rest/services/GPServer/export`

Where as a normal print service is something like this:
`/arcgis/rest/services/DEQEnviro/ExportWebMap/GPServer/Export%20Web%20Map`

The regex in the experience builder verification code is expecting something between `services/` and `/GPServer` and print proxy doesn't satisfy that.

I believe that #53 would fix this but it's a breaking change and a major overhaul for this project.

@nathankota This is probably something that needs to be prioritized at some point.

**Comment by steveoh** [comment]
Could you add a new route for experience builder to not force a breaking change?

**Comment by stdavis** [comment]
I'd rather just put in the work for #53 and do it right. But maybe the next version could be a new route.

**Comment by steveoh** [comment]
For sure. What is not doing it right about having two routes? With the middleware swap couldn't a new and existing route continue to function not breaking any clients?

**Comment by stdavis** [comment]
Nothing is broken at the moment other than EB that I know of. The break would be migrating to EB from something else.
