### ISSUE TITLE
Port to new GCP Project

### ISSUE THREAD

**Issue by stdavis** [agrc/serverless-print-proxy#22]
@steveoh would like this function moved to a new GCP project. We need to:
- [x] Deploy it to a new GCP project
- [x] Register a new DNS for this project and point it to the new project
- [x] Reach out to users and ask them to switch to the new DNS
- [x] Retire the old project once users have switched.

**Comment by stdavis** [comment]
/remind me to reach out to users in two weeks

**Comment by steveoh** [comment]
We need to migrate this to it's own project so you might want to wait until the new dns is up to reach out?

**Comment by stdavis** [comment]
Email has been sent out to users asking them to update by Sept 1st.

**Comment by stdavis** [comment]
/remind me to check the usage logs for the old service on September 8.

**Comment by stdavis** [comment]
Looks like we have a couple of accounts still making requests. One is summit county; I've sent them another email about it. The other is the account created for parcels.utah.gov. I'm seeing a fair amount of requests. However, I confirmed that I switched that app to the new URL weeks ago. @steveoh Any ideas on why we are still seeing requests for it?

**Comment by steveoh** [comment]
Not a clue, any chance you can check the referrer header to see where it is originating?

**Comment by stdavis** [comment]
I'm not logging the referrer explicitly and I couldn't find anywhere else to look. I may just have to shut it off and see who complains. I searched GitHub again to make sure that I got all of the old DNS entries.

**Comment by steveoh** [comment]
How easily could we add a log statement for the request headers and a source ip? I'm curious now how the parcel url is being used if the app was updated...

**Comment by stdavis** [comment]
I'll give it a try...

**Comment by stdavis** [comment]
I added the referer and source ip to the logs. I'll check again in a few hours...

**Comment by stdavis** [comment]
![image](https://user-images.githubusercontent.com/1326248/92654185-b6006f80-f2ac-11ea-90a2-c8dbfd002bf2.png)

I don't understand this, unless parcels.utah.gov is not updating on someone's computer...

**Comment by stdavis** [comment]
OK. The lone hold out is the summit county parcel viewer. I called Jeff from Summit county this morning and asked him if he got my emails. He said that he hasn't been into work all week before a tree fell on his house. 😬 I told him not to worry about it until he comes back to work. He said maybe next week. I'm just going to let it be for now.

**Comment by stdavis** [comment]
Summit county has switched to the new DNS. Jeff sent me an email this afternoon and I verified. BUT...I looked through the logs for today and found another app hitting the old service:
![image](https://user-images.githubusercontent.com/1326248/93146656-a027eb80-f6ac-11ea-9a36-0f1feeeaa209.png)

That's probably a bad app to break. I'll reach out to SLCo...

**Comment by stdavis** [comment]
The SLCo app has been switched to the new DNS. Now, I'm seeing WRI requests and found out that my merge request was never acted upon: https://git.dts.utah.gov/sixthfloor-east/wri/-/merge_requests/63

I @-mentioned Casey on it. Hopefully, something happens soon on that one. Is this one of those times that I'm expecting someone to be as on top of things as Steve and I'm just disappointed?

**Comment by steveoh** [comment]
I'll get it moved through. I didn't realize it was in gitlab waiting.

**Comment by stdavis** [comment]
I've deleted the old service. There's no way to shut them down. Hopefully, we are OK. I checked the logs, there are still requests coming from parcels.utah.gov and a few others but I've emailed the owners several times. There's only so much that we can do.
