### ISSUE TITLE
Switch to http-proxy-middleware

### ISSUE THREAD

**Issue by stdavis** [agrc/serverless-print-proxy#53]
[http-proxy-middleware](https://www.npmjs.com/package/http-proxy-middleware) may simplify this project.

**Comment by stdavis** [comment]
I did a little exploring with this today. It would likely mean a breaking change but it could simplify the app and accounts config. I think that you could make it so the account config would be something like this:

```js
{
	1: {
		arcgisServer: 'mapserv.utah.gov',
		quadWord: 'your-quad-word-here'
	}
}
```

And then the proxy URL would be something like:
```
https://print.agrc.utah.gov/<accountNumber>/arcgis/rest/services/path-to-real-service/
```

Then this proxy would work for any print service on the configured server.

I'm just not sure that it would be worth going through the pain of getting all of the users of this project to update their URLs.

**Comment by steveoh** [comment]
Can it work both ways allowing for a migration?

**Comment by stdavis** [comment]
I wouldn't think so. But maybe it could be a new service name and DNS. `print.agrc.utah.gov` -> `print.ugrc.utah.gov`.

**Comment by steveoh** [comment]
I like the new service idea with the proper dns
